# https://docs.drone.io/configure/pipeline/overview/

kind: pipeline
name: default

steps:
- name: install
  image: node:12
  commands:
  - npm i

- name: test
  image: node:12
  commands:
  - npm run test  

- name: build
  image: node:12
  commands:
  - npm run build
