name: Node CI

on:
- pull_request
- push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: npm install, build
      run: |
        npm ci
        npm run build
      env:
        CI: true

    - name: npm  test
      run: |
        npm test
      env:
        NODE_ENV: test
        CI: true
